#!/bin/sh

if [ "$1" = "" ]; then
        PREFIX=/home
else
        PREFIX=$1
fi

./configure --prefix=$PREFIX/wmail \
        --enable-cgibindir=$PREFIX/wmail/www/cgi-bin \
        --enable-imagedir=$PREFIX/wmail/www/image \
        --enable-imageurl=/image \
        --with-cachedir=$PREFIX/wmail/var/cache \
        --enable-webpass=no \
        --without-ispell \
        --with-maxmsgsize=5242880 --with-maxformargsize=5000000\
        --enable-maxpurge=7 \
        --without-authpam --without-authuserdb --without-authpwd --without-authshadow \
        --without-authldap --without-authdaemon --with-authvchkpw \
        --with-defaultlang=zh-cn --enable-unicode  \
        --with-fcgi \
        --enable-https=auto \
        --with-cacheowner=vpopmail

make configure-check
make 
make check
make install-strip
make install-configure
