#!/usr/bin/perl

require 5.002 ;

use strict;
use warnings;

use vars qw($XOR $BLOCKSIZE $BLOCKNUM $HEADERSIZE $CRYPT_MAGIC_1 $CRYPT_MAGIC_2
	    $size $mode $line $Fingerprint $file $block
	   ) ;

$XOR	 	= 'okboy&zixia@2004-03-07' ;
$BLOCKSIZE       = length $XOR ;
$BLOCKNUM	 = 512;

$HEADERSIZE      = 2 ;
$CRYPT_MAGIC_1   = 0xfe ;
$CRYPT_MAGIC_2   = 0x01 ;

$Fingerprint     = pack ("C*", $CRYPT_MAGIC_1, $CRYPT_MAGIC_2) ;

die "Usage: encrypt file...\n"
  unless @ARGV ;

# Loop throught each file in turn.
foreach $file (@ARGV)
{

    if (! -T $file)
    {
	print "Skipping directory $file\n" if -d $file ;
	print "Skipping non-text $file\n" if ! -d $file ;
	next ;
    }

    open (F, "<$file") or die "Cannot open $file: $!\n" ;
    open (O, ">${file}.pe") or die "Cannot open ${file}.pe: $!\n" ;
    binmode O;

    # Get the mode
    $mode = (stat F)[2] ;

    # Check for "#!perl" line
    $line = <F> ;

    if ( $line =~ /^#!/ ) 
      { print O $line }
    else
      { seek F, 0, 0 }
    
    print O "use AKA::Loader ;\n" ;
    print O $Fingerprint ;


    $block = '';
    while ($size = read(F, $block, $BLOCKSIZE) )
    {
        print O ($block ^ substr($XOR, 0, length $block)) ;
    }

    close F ;
    close O ;

    unlink ($file) 
	or die "Could not remove '$file': $!\n" ;

    my $newfile;
    if ( $file=~/^(.+)\.pl/ ){
	$newfile = $1;
    }else{
	$newfile = $file;
    }
    rename ("${file}.pe", $newfile) 
	or die "Could not rename $file.pe to $file: $!\n" ;

    chmod $mode, $newfile unless $^O eq 'MSWin32' ;

    print "encrypted $file to $newfile\n" ;
}

